import type { Preview } from '@storybook/react';
import React from 'react';

const LIGHT_THEME_VARS: Record<string, string> = {
  '--glyph-bg': '#f4f6fa',
  '--glyph-text': '#1a2035',
  '--glyph-text-muted': '#6b7a94',
  '--glyph-heading': '#0a0e1a',
  '--glyph-link': '#0a9d7c',
  '--glyph-link-hover': '#088a6c',
  '--glyph-border': '#d0d8e4',
  '--glyph-border-strong': '#a8b5c8',
  '--glyph-surface': '#e8ecf3',
  '--glyph-surface-raised': '#f4f6fa',
  '--glyph-accent': '#0a9d7c',
  '--glyph-accent-hover': '#088a6c',
  '--glyph-accent-subtle': '#e6f6f2',
  '--glyph-accent-muted': '#b0ddd0',
  '--glyph-font-body': '"Inter", "Helvetica Neue", system-ui, sans-serif',
  '--glyph-font-heading': '"Inter", "Helvetica Neue", system-ui, sans-serif',
  '--glyph-font-mono': 'ui-monospace, "Cascadia Code", "Fira Code", monospace',
  '--glyph-radius-sm': '0.375rem',
  '--glyph-radius-md': '0.5rem',
  '--glyph-radius-lg': '0.75rem',
  '--glyph-spacing-xs': '0.25rem',
  '--glyph-spacing-sm': '0.5rem',
  '--glyph-spacing-md': '1rem',
  '--glyph-callout-info-bg': '#e6f2fa',
  '--glyph-callout-info-border': '#38bdf8',
  '--glyph-callout-warning-bg': '#fef3e2',
  '--glyph-callout-warning-border': '#fb923c',
  '--glyph-callout-error-bg': '#fde8e8',
  '--glyph-callout-error-border': '#f87171',
  '--glyph-callout-tip-bg': '#e6f6f0',
  '--glyph-callout-tip-border': '#22c55e',
  '--glyph-table-border': '#d0d8e4',
  '--glyph-table-header-bg': '#e8ecf3',
  '--glyph-grid': '#d0d8e4',
  '--glyph-tooltip-bg': 'rgba(10, 14, 26, 0.9)',
  '--glyph-tooltip-text': '#f4f6fa',
  '--glyph-timeline-line': '#d0d8e4',
  '--glyph-shadow-sm': '0 1px 3px rgba(0,0,0,0.1)',
  '--glyph-shadow-md': '0 4px 12px rgba(0,0,0,0.15)',
  '--glyph-shadow-lg': '0 8px 30px rgba(0,0,0,0.2)',
  '--glyph-shadow-glow': 'none',
  '--glyph-text-shadow': 'none',
  '--glyph-backdrop': 'none',
  '--glyph-gradient-accent': 'linear-gradient(135deg, #0a9d7c, #22c55e)',
  '--glyph-transition': '0.2s ease',
  '--glyph-opacity-muted': '0.7',
  '--glyph-opacity-disabled': '0.4',
  '--glyph-focus-ring': '0 0 0 2px #0a9d7c',
  '--glyph-node-fill-opacity': '0.85',
  '--glyph-node-radius': '3',
  '--glyph-node-stroke-width': '1.5',
  '--glyph-node-label-color': '#fff',
  '--glyph-edge-color': '#a8b5c8',
  '--glyph-icon-stroke': '#fff',
  '--glyph-icon-stroke-width': '1.5',
  '--glyph-kpi-positive': '#16a34a',
  '--glyph-kpi-negative': '#dc2626',
  '--glyph-kpi-neutral': '#6b7a94',
  '--glyph-comparison-yes': '#16a34a',
  '--glyph-comparison-no': '#dc2626',
  '--glyph-comparison-partial': '#d97706',
  '--glyph-codediff-add-bg': 'rgba(22, 163, 106, 0.1)',
  '--glyph-codediff-add-color': '#166534',
  '--glyph-codediff-del-bg': 'rgba(220, 38, 38, 0.1)',
  '--glyph-codediff-del-color': '#991b1b',
  '--glyph-codediff-gutter-bg': '#e8ecf3',
  '--glyph-infographic-track': '#e0e4ea',
  '--glyph-infographic-color-1': '#3b82f6',
  '--glyph-infographic-color-2': '#22c55e',
  '--glyph-infographic-color-3': '#f59e0b',
  '--glyph-infographic-color-4': '#ef4444',
  '--glyph-infographic-section-divider': '#d0d8e4',
};

const DARK_THEME_VARS: Record<string, string> = {
  '--glyph-bg': '#0a0e1a',
  '--glyph-text': '#d4dae3',
  '--glyph-text-muted': '#6b7a94',
  '--glyph-heading': '#edf0f5',
  '--glyph-link': '#00d4aa',
  '--glyph-link-hover': '#33e0be',
  '--glyph-border': '#1a2035',
  '--glyph-border-strong': '#2a3550',
  '--glyph-surface': '#0f1526',
  '--glyph-surface-raised': '#162038',
  '--glyph-accent': '#00d4aa',
  '--glyph-accent-hover': '#33e0be',
  '--glyph-accent-subtle': '#0a1a1a',
  '--glyph-accent-muted': '#1a4a3a',
  '--glyph-font-body': '"Inter", "Helvetica Neue", system-ui, sans-serif',
  '--glyph-font-heading': '"Inter", "Helvetica Neue", system-ui, sans-serif',
  '--glyph-font-mono': 'ui-monospace, "Cascadia Code", "Fira Code", monospace',
  '--glyph-radius-sm': '0.375rem',
  '--glyph-radius-md': '0.5rem',
  '--glyph-radius-lg': '0.75rem',
  '--glyph-spacing-xs': '0.25rem',
  '--glyph-spacing-sm': '0.5rem',
  '--glyph-spacing-md': '1rem',
  '--glyph-callout-info-bg': '#0a1526',
  '--glyph-callout-info-border': '#38bdf8',
  '--glyph-callout-warning-bg': '#1a1608',
  '--glyph-callout-warning-border': '#fb923c',
  '--glyph-callout-error-bg': '#1f0e0e',
  '--glyph-callout-error-border': '#f87171',
  '--glyph-callout-tip-bg': '#0a1a14',
  '--glyph-callout-tip-border': '#22c55e',
  '--glyph-table-border': '#1a2035',
  '--glyph-table-header-bg': '#0f1526',
  '--glyph-table-header-color': '#d4dae3',
  '--glyph-table-row-alt-bg': '#121a2c',
  '--glyph-table-cell-color': '#d4dae3',
  '--glyph-table-footer-bg': '#0f1526',
  '--glyph-table-footer-color': '#d4dae3',
  '--glyph-grid': '#1a2035',
  '--glyph-tooltip-bg': 'rgba(0, 0, 0, 0.9)',
  '--glyph-tooltip-text': '#d4dae3',
  '--glyph-timeline-line': '#2a3550',
  '--glyph-shadow-sm': '0 1px 3px rgba(0,0,0,0.4)',
  '--glyph-shadow-md': '0 4px 12px rgba(0,0,0,0.5)',
  '--glyph-shadow-lg': '0 8px 30px rgba(0,0,0,0.6)',
  '--glyph-shadow-glow': '0 0 15px rgba(0,212,170,0.3)',
  '--glyph-text-shadow': 'none',
  '--glyph-backdrop': 'none',
  '--glyph-gradient-accent': 'linear-gradient(135deg, #00d4aa, #00e5ff)',
  '--glyph-transition': '0.2s ease',
  '--glyph-opacity-muted': '0.7',
  '--glyph-opacity-disabled': '0.4',
  '--glyph-focus-ring': '0 0 0 2px #00d4aa',
  '--glyph-node-fill-opacity': '0.85',
  '--glyph-node-radius': '3',
  '--glyph-node-stroke-width': '1.5',
  '--glyph-node-label-color': '#fff',
  '--glyph-edge-color': '#6b7a94',
  '--glyph-icon-stroke': '#fff',
  '--glyph-icon-stroke-width': '1.5',
  '--glyph-kpi-positive': '#22c55e',
  '--glyph-kpi-negative': '#f87171',
  '--glyph-kpi-neutral': '#6b7a94',
  '--glyph-comparison-yes': '#22c55e',
  '--glyph-comparison-no': '#f87171',
  '--glyph-comparison-partial': '#fbbf24',
  '--glyph-codediff-add-bg': 'rgba(34, 197, 94, 0.15)',
  '--glyph-codediff-add-color': '#86efac',
  '--glyph-codediff-del-bg': 'rgba(248, 113, 113, 0.15)',
  '--glyph-codediff-del-color': '#fca5a5',
  '--glyph-codediff-gutter-bg': '#0f1526',
  '--glyph-infographic-track': '#2a3550',
  '--glyph-infographic-color-1': '#60a5fa',
  '--glyph-infographic-color-2': '#4ade80',
  '--glyph-infographic-color-3': '#fbbf24',
  '--glyph-infographic-color-4': '#f87171',
  '--glyph-infographic-section-divider': '#1a2035',
};

function ThemeWrapper({ children, theme }: { children: React.ReactNode; theme: 'light' | 'dark' }) {
  const vars = theme === 'dark' ? DARK_THEME_VARS : LIGHT_THEME_VARS;
  const style: React.CSSProperties = {
    padding: '1rem',
    backgroundColor: theme === 'dark' ? '#0a0e1a' : '#f4f6fa',
    color: theme === 'dark' ? '#d4dae3' : '#1a2035',
    minHeight: '100vh',
  };

  // Merge CSS custom properties into the style object
  for (const [key, value] of Object.entries(vars)) {
    (style as Record<string, string>)[key] = value;
  }

  return React.createElement('div', { style }, children);
}

const preview: Preview = {
  globalTypes: {
    theme: {
      description: 'Global theme for components',
      toolbar: {
        title: 'Theme',
        icon: 'circlehollow',
        items: ['light', 'dark'],
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: {
    theme: 'light',
  },
  decorators: [
    (Story, context) => {
      const theme = (context.globals['theme'] as 'light' | 'dark') || 'light';
      return React.createElement(ThemeWrapper, { theme }, React.createElement(Story));
    },
  ],
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
